import { memo } from 'react';
import { useLingui } from '@lingui/react/macro';
import { percentFormat } from '@repo/lib/format';
import { useGlobalStore } from '@/common';
import {
  DetailMetricCard,
  DetailMetricsCard,
} from '@/containers/pools/PoolsDetail/components/detailShared';
import { useVaultDetail } from '@/queries/bsc/vaults';
import {
  useVaultDepositCapMetrics,
  useVaultTotalEarnedFeesUsd,
} from '@/stores/synthetics/marketsData/selectors';
import { formatUsdValue } from './formatUsdValue';

type VaultInfoCardProps = {
  vaultAddress: string;
  isLoading?: boolean;
};

const VaultDetailBanner = memo(function VaultDetailBanner({
  vaultAddress,
}: VaultInfoCardProps) {
  const { t } = useLingui();

  const { tvlUsd } = useVaultDepositCapMetrics(vaultAddress);
  const vaultDetailQuery = useVaultDetail(vaultAddress);
  const vaultDetail = vaultDetailQuery.data?.data;
  const totalEarnedFeesUsd = useVaultTotalEarnedFeesUsd(vaultAddress);
  const usdAmountDisplayDecimal = useGlobalStore(
    (state) => state.usdAmountDisplayDecimal,
  );
  const hasTvl = tvlUsd !== undefined;
  const hasTotalEarnedFees = totalEarnedFeesUsd !== undefined;
  const hasNetApy = vaultDetail?.net_apy !== undefined;
  const netApy = vaultDetail?.net_apy;

  const tvlValue = formatUsdValue(tvlUsd, usdAmountDisplayDecimal);
  const totalEarnedFeesValue = formatUsdValue(
    totalEarnedFeesUsd,
    usdAmountDisplayDecimal,
  );
  return (
    <div className="max-md:bg-bg-2 max-md:rounded-2xl max-md:p-3">
      <DetailMetricsCard contentClassName="grid grid-cols-2 gap-x-3 gap-y-3 md:flex md:items-start md:gap-3">
        <DetailMetricCard
          label={t`Net APY`}
          value={
            hasNetApy
              ? percentFormat(netApy!, 2, {
                  showMinDecimalValue: true,
                  stripTrailingZeros: true,
                })
              : '--'
          }
          tooltip={t`Annualized vault yield after performance fee.`}
          valueClassName={
            Number(vaultDetail?.net_apy ?? 0) >= 0 ? 'text-up' : 'text-down'
          }
        />
        <DetailMetricCard
          label={t`TVL`}
          value={hasTvl ? tvlValue : '--'}
          tooltip={t`Total vault assets under management. Reflects real-time vault value including active trader exposure across the underlying pools.`}
        />
        <DetailMetricCard
          className="col-span-2 md:col-span-1"
          label={t`Total Earned Fees`}
          value={hasTotalEarnedFees ? totalEarnedFeesValue : '--'}
          tooltip={
            <div className="flex flex-col gap-2">
              <div className="text-t-1100">{t`Native APY + Strategy Earnings - Fees`}</div>
              <div>
                {t`Cumulative fees generated by the underlying pools through all trading activity, together with returns from the vault's strategy, net of protocol and strategy fees.`}
              </div>
            </div>
          }
        />
      </DetailMetricsCard>
    </div>
  );
});

export { VaultDetailBanner };
