'use client';

import { useEffect, useMemo, useState } from 'react';
import { usePathname } from 'next/navigation';
import { USD_DECIMALS } from '@hertzflow/sdk-v2/utils/numbers';
import { Trans, useLingui } from '@lingui/react/macro';
import { cn, MEDIA_SIZES, useMediaQuery } from '@repo/ui';
import { useGlobalStore } from '@/common';
import { OverviewMetricItem } from '@/common/components';
import VideoLayer from '@/common/components/VideoLayer';
import { useHydrated } from '@/common/hooks/useHydrated';
import { useRafReady } from '@/common/hooks/useRafReady';
import ModuleCard from '@/components/ModuleCard';
import { convertBigintToHumanReadable } from '@/lib/shared/utils';
import type { fetchPoolsList, fetchPoolsOverview } from '@/services/rest/pools';
import { usePoolsOverviewFields } from '@/stores/synthetics/marketsData/selectors';
import PoolsList from './components/PoolsList';
import PoolsOverviewSkeleton from './Skeleton';

type PoolsOverviewProps = {
  initialPoolsListData?: Awaited<ReturnType<typeof fetchPoolsList>>;
  initialPoolsOverviewData?: Awaited<ReturnType<typeof fetchPoolsOverview>>;
};

export const PoolsOverview = (props: PoolsOverviewProps) => {
  const canMountOverview = useRafReady();

  if (!canMountOverview) {
    return <PoolsOverviewSkeleton />;
  }

  return <PoolsOverviewContent {...props} />;
};

const PoolsOverviewContent = ({
  initialPoolsListData,
  initialPoolsOverviewData,
}: PoolsOverviewProps) => {
  const { t } = useLingui();
  const mediaSz = useMediaQuery();
  const isHydrated = useHydrated();
  const isMobile = isHydrated && mediaSz === MEDIA_SIZES.SM;
  const pathname = usePathname();

  const [shouldAnimate, setShouldAnimate] = useState(false);
  const [boundaryEl, setBoundaryEl] = useState<HTMLDivElement | null>(null);

  useEffect(() => {
    const prevPath = sessionStorage.getItem('prevPath') ?? '';
    const isFromDetail = /\/pools\/[^/]+$/.test(prevPath);
    const isOverview = /\/pools$/.test(pathname);
    setShouldAnimate(isFromDetail && isOverview);
  }, [pathname]);
  const usdAmountDisplayDecimal = useGlobalStore(
    (state) => state.usdAmountDisplayDecimal,
  );
  const { totalTvl, totalEarnedFees, yourDeposits, yourEarnedFees } =
    usePoolsOverviewFields(initialPoolsOverviewData);

  const metrics = useMemo(
    () => [
      {
        title: t`TVL`,
        value: totalTvl,
        tips: (
          <div className="flex flex-col gap-2">
            <div className="text-t-1100">
              {t`Pool Collateral Balance + Net Unrealized PnL + Total Earned Fees`}
            </div>
            <div>
              {t`Total pool assets under management in all pools. Reflects sum of real-time pool value including active trader exposure.`}
            </div>
          </div>
        ),
      },
      {
        title: t`Total Earned Fees`,
        value: totalEarnedFees,
        tips: (
          <div className="flex flex-col gap-2">
            <div className="text-t-1100">{t`Native APY - Fees`}</div>
            <div>
              {t`Cumulative fees generated by the pool through all trading activity, net of protocol fees in all pools.`}
            </div>
          </div>
        ),
      },
      {
        title: t`Your Holdings`,
        value: yourDeposits,
        tips: (
          <div>
            {t`Total value of your LP tokens in all pools. Value fluctuates based on pool performance and trader PnL.`}
          </div>
        ),
      },
      {
        title: t`Your Unrealised PnL`,
        value: yourEarnedFees,
        tips: (
          <div>
            {t`Your share of the fees and uPnL generated by the pool through all trading activity, net of protocol fees in all pools. Accrues proportionally to your deposit size and duration.`}
          </div>
        ),
      },
    ],
    [t, totalEarnedFees, totalTvl, yourDeposits, yourEarnedFees],
  );

  return (
    <div
      className={cn(
        'h-[calc(100dvh-56px)] overflow-y-auto md:flex md:h-full md:flex-col md:gap-1 md:overflow-x-hidden md:overflow-y-auto md:p-1',
        shouldAnimate &&
          'animate-in slide-in-from-left-10 fade-in md:duration-300',
      )}
    >
      <div className="flex flex-col gap-y-4 md:shrink-0 md:flex-row md:gap-1">
        <ModuleCard className="relative flex flex-1 flex-col gap-8 overflow-hidden rounded-none p-0 max-md:gap-6 md:rounded-2xl">
          <div className="px-4 pt-6 md:pt-4">
            <VideoLayer
              src="/trade-static/videos/light.mp4"
              className="pointer-events-none absolute inset-0 hidden h-full w-full rotate-180 object-cover md:block"
              visibleClassName="opacity-60 mix-blend-screen"
            />
            <div className="relative z-10">
              <h2 className="font-borna font-medium max-md:text-xl md:mb-0 md:w-[50%] md:min-w-[471px]">
                <Trans>
                  Provide market-specific liquidity with independent risk and
                  asset management.
                </Trans>
              </h2>
            </div>
          </div>
          <div className="to-bg-1 pointer-events-none absolute inset-x-0 bottom-0 z-10 h-24 bg-gradient-to-b from-transparent md:hidden" />
          <div ref={setBoundaryEl} className="relative z-20 px-2 pb-6 md:pb-2">
            <div className="grid grid-cols-2 gap-4 md:grid-cols-4 md:gap-2">
              {metrics.map((metric) => (
                <OverviewMetricItem
                  key={metric.title}
                  title={metric.title}
                  rawValue={
                    metric.value === undefined
                      ? undefined
                      : convertBigintToHumanReadable(metric.value, USD_DECIMALS)
                  }
                  formatDecimal={usdAmountDisplayDecimal}
                  formatOptions={{
                    style: 'currency',
                    currency: 'USD',
                    showMinDecimalValue: true,
                    stripTrailingZeros: true,
                  }}
                  isLoading={!isHydrated || metric.value === undefined}
                  skeletonClassName="h-[17px] w-16 md:w-24"
                  wrapClassName="h-[17px]"
                  triggerClassName="cursor-pointer rounded-xl p-2"
                  tooltipContentProps={
                    isMobile
                      ? undefined
                      : {
                          sideOffset: 0,
                          className: 'md:max-w-100',
                          collisionBoundary: boundaryEl
                            ? [boundaryEl]
                            : undefined,
                          collisionPadding: { top: -500, bottom: -500 },
                        }
                  }
                  valueClassName="md:text-sm/tight"
                  tips={metric.tips}
                />
              ))}
            </div>
          </div>
        </ModuleCard>
        {isMobile ? null : (
          <ModuleCard className="relative w-1/2 overflow-hidden p-0">
            <p className="absolute top-1/2 left-10 z-20 -translate-y-1/2 text-base/tight font-medium whitespace-nowrap">
              {t`Open Liquidity. Modular Yield.`}
            </p>
            <VideoLayer
              src="/trade-static/videos/pool.mp4"
              className="pointer-events-none absolute top-0 right-0 h-full w-full object-cover"
              visibleClassName=""
            />
          </ModuleCard>
        )}
      </div>
      <div className="min-w-0 md:shrink-0">
        <ModuleCard className="flex flex-col md:p-3">
          <div className="max-md:pb-6">
            <PoolsList initialData={initialPoolsListData} />
          </div>
        </ModuleCard>
      </div>
    </div>
  );
};
