export const STATIC_CONFIG_CACHE_TIME = 60_000;

export const DYNAMIC_DATA_CACHE_TIME = 20_000;

/** @deprecated Use DYNAMIC_DATA_CACHE_TIME instead */
export const DEFAULT_REFETCH_INTERVAL = DYNAMIC_DATA_CACHE_TIME;

/** @deprecated Use DYNAMIC_DATA_CACHE_TIME instead */
export const LIVE_REFRESH_INTERVAL = DYNAMIC_DATA_CACHE_TIME;

/** @deprecated Use DYNAMIC_DATA_CACHE_TIME instead */
export const FREQUENT_MULTICALL_REFRESH_INTERVAL = DYNAMIC_DATA_CACHE_TIME;

/** @deprecated Use DYNAMIC_DATA_CACHE_TIME instead */
export const RATE_REFRESH_INTERVAL = DYNAMIC_DATA_CACHE_TIME;

/** @deprecated Use STATIC_CONFIG_CACHE_TIME instead */
export const CONFIG_UPDATE_INTERVAL = STATIC_CONFIG_CACHE_TIME;
