'use client';
import { memo, useMemo } from 'react';
import { USD_DECIMALS } from '@hertzflow/sdk-v2/utils/numbers';
import { useLingui } from '@lingui/react/macro';
import { formatUnits } from 'viem';
import { percentFormat, unitFormat } from '@repo/lib/format';
import { useGlobalStore } from '@/common';
import type { PoolDetailQueryData } from '@/queries/bsc/pools';
import { usePoolTvlUsd } from '@/stores/synthetics/marketsData/selectors';
import type { PoolDetailData } from '@/stores/synthetics/marketTokens/selectors';
import { DetailMetricCard, DetailMetricsCard } from './detailShared';

type PoolDetailBannerProps = {
  data?: Partial<PoolDetailData> | null;
  marketAddress: string;
  initialData?: PoolDetailQueryData;
};

const PoolDetailBanner = memo(function PoolDetailBanner({
  data,
  marketAddress,
  initialData,
}: PoolDetailBannerProps) {
  const usdAmountDisplayDecimal = useGlobalStore(
    (state) => state.usdAmountDisplayDecimal,
  );
  const { t } = useLingui();
  const tvlUsd = usePoolTvlUsd(marketAddress, initialData);
  const hasTvl = tvlUsd !== undefined;
  const hasTotalEarnedFees = data?.totalEarnedFees !== undefined;
  const hasApy = data?.feeApyRaw !== undefined;

  const totalEarnedFeesValue =
    data?.totalEarnedFees !== undefined
      ? unitFormat(data.totalEarnedFees, usdAmountDisplayDecimal, {
          style: 'currency',
          currency: 'USD',
          showMinDecimalValue: true,
        })
      : '';

  const tvlValue =
    tvlUsd !== undefined
      ? unitFormat(formatUnits(tvlUsd, USD_DECIMALS), usdAmountDisplayDecimal, {
          style: 'currency',
          currency: 'USD',
          showMinDecimalValue: true,
          stripTrailingZeros: true,
        })
      : '';

  const apyValue = useMemo(() => {
    if (data?.feeApyRaw === undefined) return '--';
    return percentFormat(data.feeApyRaw, 2, {
      showMinDecimalValue: true,
      stripTrailingZeros: true,
    });
  }, [data?.feeApyRaw]);

  return (
    <div className="max-md:bg-bg-2 max-md:rounded-2xl max-md:p-3">
      <DetailMetricsCard contentClassName="grid grid-cols-2 gap-x-3 gap-y-3 md:flex md:items-start md:gap-3">
        <DetailMetricCard
          label={t`APY`}
          value={hasApy ? apyValue : '--'}
          tooltip={t`Annualized pool yield from trading fees for this market.`}
          valueClassName={
            Number(data?.feeApyRaw ?? 0) >= 0 ? 'text-up' : 'text-down'
          }
        />
        <DetailMetricCard
          label={t`TVL`}
          value={hasTvl ? tvlValue : '--'}
          tooltip={t`Total pool assets under management. Reflects real-time pool value including active trader exposure.`}
        />
        <DetailMetricCard
          className="col-span-2 md:col-span-1"
          label={t`Total Earned Fees`}
          value={hasTotalEarnedFees ? totalEarnedFeesValue : '--'}
          tooltip={
            <div className="flex flex-col gap-2">
              <div className="text-t-1100">{t`Native APY - Fees`}</div>
              <div>
                {t`Cumulative fees generated by the pool through all trading activity, net of protocol fees.`}
              </div>
            </div>
          }
        />
      </DetailMetricsCard>
    </div>
  );
});

export { PoolDetailBanner };
